### ISSUE TITLE
Run geom build test, python 3.9 FAIL

### ISSUE THREAD

**Issue by felicio93** [noaa-ocs-modeling/OCSMesh#163]
This is the error message:
```
Run source tests/cli/build_geom.sh
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/bin/ocsmesh", line 5, in <module>
    from ocsmesh.__main__ import main
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/ocsmesh/__init__.py", line 22, in <module>
    raise e
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/ocsmesh/__init__.py", line 10, in <module>
    import jigsawpy  # noqa: F401
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jigsawpy-1.0.0-py3.9.egg/jigsawpy/__init__.py", line 62, in <module>
    from jigsawpy import jigsaw, libsaw
  File "/opt/hostedtoolcache/Python/3.9.[19](https://github.com/noaa-ocs-modeling/OCSMesh/actions/runs/9764039154/job/26951365004?pr=162#step:8:20)/x64/lib/python3.9/site-packages/jigsawpy-1.0.0-py3.9.egg/jigsawpy/libsaw.py", line 76, in <module>
    JLIB = ct.cdll.LoadLibrary(str(JLIBNAME))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libjigsaw.so: cannot open shared object file: No such file or directory
Error: Process completed with exit code 1.
```

I will try run the setup locally on py3.9 and see why it fails

**Comment by SorooshMani-NOAA** [comment]
The main problem is that the latest `scipy` is **not** supported on Py3.9, but I don't understand why it tries to install the latest `scipy`!

**Comment by felicio93** [comment]
We dropped the support for Python 3.9
