### ISSUE TITLE
setup.py:_check_gcc_version fails with unexpected return values "too many values to unpack"

### ISSUE THREAD

**Issue by platipodium** [noaa-ocs-modeling/OCSMesh#47]
When running `setup.py` on Mac M1 with  macports-installed gcc, the function `check_gcc_version` fails to decode the string returned by `system("cpp --version")`

```
Traceback (most recent call last):
  File "/Users/Lemmen/devel/noaa/OCSMesh/setup.py", line 85, in <module>
    setuptools.setup(
  File "/opt/anaconda3/envs/ocsmesh/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/opt/anaconda3/envs/ocsmesh/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/opt/anaconda3/envs/ocsmesh/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/opt/anaconda3/envs/ocsmesh/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda3/envs/ocsmesh/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/opt/anaconda3/envs/ocsmesh/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/Users/Lemmen/devel/noaa/OCSMesh/setup.py", line 55, in run
    gcc, cpp = self._check_gcc_version()
  File "/Users/Lemmen/devel/noaa/OCSMesh/setup.py", line 74, in _check_gcc_version
    major, minor, patch = subprocess.check_output(
ValueError: too many values to unpack (expected 3)
```

The shell itself would return  the following 
```
> which c++
/usr/bin/c++
> c++ --version
Apple clang version 14.0.0 (clang-1400.0.29.201)

> which cpp
/opt/local/bin/cpp
> cpp --version
cpp (MacPorts gcc12 12.2.0_2+stdlib_flag) 12.2.0
```

It seems that there are two problems:

1.  assumptions that `c++` gives a good `cpp`
2. inability to decode the version information given back by `clang` or `gcc`

**Comment by platipodium** [comment]
If you really depend on `gnu` `gcc`, then the subroutine should look for `g++` not `c++`, as the latter may point to non-gnu c compilers.

**Comment by SorooshMani-NOAA** [comment]
Thanks, this is helpful. I'll keep that in mind when I look into fixing this.

**Comment by acroucher** [comment]
I just struck a similar issue when trying to install on an HPC where the output from `c++ --version` is `c++ (GCC) 12.1.0 20220506 (HPE)` - so the version number is not the last item on the line.

Perhaps we could use a regexp to find the version number in the line? e.g.

```python
import re
cpp = shutil.which("c++")
line = subprocess.check_output([cpp, "--version"]).decode('utf-8').split('\n')[0]
m = re.search('(\d+\.)?(\d+\.)?(\d+)', line)
if m:
  major, minor, patch = line[m.start(): m.end()].split('.')
  current_version = float(f"{major}.{minor}")
  # etc
```

**Comment by SorooshMani-NOAA** [comment]
@acroucher thanks for your feedback. This needs to be addressed in OCSMesh at some point.

Ideally this shouldn't really be here though. That's because it is compiling dependencies "manually". The best solution is to just name the dependency and it should either be installed before installing OCSMesh or be installed from PyPI; the latter is not possible since JigsaswPy is not currently released on PyPI.

As a short term solution (other than changing the `setup.py` I'd suggest either using `conda` to install `jigsawpy` (the easiest) or also download that repo (https://github.com/dengwirda/jigsaw-python) and follow its instructions for installing (basically just call `python setup.py build_external` and then `python setup.py install` in that repo)

I'm also waiting for conda-forge to accept the pull request so that you can install ocsmesh directly from `conda`: https://github.com/conda-forge/staged-recipes/pull/22927
