### ISSUE TITLE
Support for Python `3.10`

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/OCSMesh#49]
Currently OCSMesh only supports Python `3.7` to `3.9`. Add support for versions `3.10`~and `3.11`~!

`3.11` dropped needs to wait for `numba`: https://github.com/numba/numba/issues/8304

**Comment by SorooshMani-NOAA** [comment]
Trying `3.8` to `3.10` (due to `numba` issue with `3.11` runs into an issue with `numpy` and `scipy`.

Up to now `numpy` was restricted to be `>=1.21,<1.23` and `scipy` to be `<1.8` since later `scipy` versions dropped support for Python `3.7`. No that limitation is lifted and on both `conda` and `pip` functional test it fails due to:
```
ERROR: test_hfun_coll_cfl_constraint (hfun.SizeFunctionWithCourantNumConstraint)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/OCSMesh/OCSMesh/tests/api/hfun.py", line 445, in test_hfun_coll_cfl_constraint
    mesh.interpolate([rast1, rast2], method='nearest', nprocs=1)
  File "/home/runner/work/OCSMesh/OCSMesh/ocsmesh/mesh/mesh.py", line 385, in interpolate
    res = [_mesh_interpolate_worker(
  File "/home/runner/work/OCSMesh/OCSMesh/ocsmesh/mesh/mesh.py", line 385, in <listcomp>
    res = [_mesh_interpolate_worker(
  File "/home/runner/work/OCSMesh/OCSMesh/ocsmesh/mesh/mesh.py", line 2104, in _mesh_interpolate_worker
    _values = f(coords[_idxs])
  File "/opt/hostedtoolcache/Python/3.9.[16](https://github.com/noaa-ocs-modeling/OCSMesh/actions/runs/3914654143/jobs/6691960808#step:14:17)/x64/lib/python3.9/site-packages/scipy-1.10.0-py3.9-linux-x86_64.egg/scipy/interpolate/_rgi.py", line 344, in __call__
    indices, norm_distances = self._find_indices(xi.T)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/scipy-1.10.0-py3.9-linux-x86_64.egg/scipy/interpolate/_rgi.py", line 499, in _find_indices
    return find_indices(self.grid, xi)
  File "_rgi_cython.pyx", line 95, in scipy.interpolate._rgi_cython.find_indices
  File "stringsource", line 660, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 350, in View.MemoryView.memoryview.__cinit__
ValueError: ndarray is not C-contiguous
```
Note that with newer Python version if `scipy` and `numpy` are still restricted this issue doesn't occur. One of the tests that failed has:
```
python=3.9.16
numpy=1.24.1
scipy=1.10.0
```

**Comment by SorooshMani-NOAA** [comment]
The issue seems to be here at https://github.com/scipy/scipy/blob/dde50595862a4f9cede24b5d1c86935c30f1f88a/scipy/interpolate/_rgi.py#L344
where the cython code is expecting a c-contiguous array, but since our input array is c-contiguous and it's transpose is not, we run into this issue.

Why do they transpose?!

**Comment by SorooshMani-NOAA** [comment]
Upon further investigation, it seems that the issue is not the argument passed to `__call__` but the parameter passed to constructor of the `RegularGridInterpolator`.

**Comment by SorooshMani-NOAA** [comment]
The issue is resolved by creating contiguous arrays from the points input to the interpolator constructor by calling `np.ascontiguousarray`
