### ISSUE TITLE
Mesh+Geom: get_multipolygon() throws "TypeError: 'MultiPolygon' object is not iterable"

### ISSUE THREAD

**Issue by rjdmartins** [noaa-ocs-modeling/OCSMesh#63]
**Description:**
I'm trying some of the examples provided from this documentation (https://repository.library.noaa.gov/view/noaa/33879), and they do not work in OCSMesh 1.1.1.

I'm trying to load a .gr3 mesh (already EPSG:4326) from Portugal using Mesh object (mesh), and then call it into a Geom object (geom).

```
import os, sys
import json

sys.path.append('/ocsmesh') #ocsmesh source directory

import geopandas as gpd
from shapely.geometry import LineString, MultiLineString, Polygon, Point
from shapely.ops import unary_union, polygonize
from ocsmesh import Raster, Geom, Hfun, Mesh, JigsawDriver, utils
import pyproj

mesh = Mesh.open('/_app/mesh_examples/leixoes_utm_hgrid.gr3')
geom = Geom(mesh)
geom.get_multipolygon()
```

When calling geom.get_multipolygon() or geom.msh_t(), I was expecting to provide the multipolygon object, but throws "TypeError: 'MultiPolygon' object is not iterable".

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ocsmesh/ocsmesh/geom/mesh.py", line 100, in get_multipolygon
    return self.mesh.hull.multipolygon()
  File "/ocsmesh/ocsmesh/mesh/mesh.py", line 1060, in multipolygon
    mp = self.implode().iloc[0].geometry
  File "/ocsmesh/ocsmesh/mesh/mesh.py", line 1029, in implode
    in self().itertuples()])},
  File "/ocsmesh/ocsmesh/mesh/mesh.py", line 949, in __call__
    for bnd_id in np.unique(self.rings()['bnd_id'].tolist()):
  File "/ocsmesh/ocsmesh/mesh/mesh.py", line 739, in __call__
    for poly in polys:
TypeError: 'MultiPolygon' object is not iterable
geom.msh_t()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ocsmesh/ocsmesh/geom/base.py", line 88, in msh_t
    self.get_multipolygon(**kwargs),
  File "/ocsmesh/ocsmesh/geom/mesh.py", line 100, in get_multipolygon
    return self.mesh.hull.multipolygon()
  File "/ocsmesh/ocsmesh/mesh/mesh.py", line 1060, in multipolygon
    mp = self.implode().iloc[0].geometry
  File "/ocsmesh/ocsmesh/mesh/mesh.py", line 1029, in implode
    in self().itertuples()])},
  File "/ocsmesh/ocsmesh/mesh/mesh.py", line 949, in __call__
    for bnd_id in np.unique(self.rings()['bnd_id'].tolist()):
  File "/ocsmesh/ocsmesh/mesh/mesh.py", line 739, in __call__
    for poly in polys:
TypeError: 'MultiPolygon' object is not iterable
```

The interesting part is, if instead I call mesh.get_multipolygon() or mesh.msh_t, they return the objects as expected.

```
mesh.get_multipolygon()
<MULTIPOLYGON (((522123.205 4505416.373, 520599.393 4505420.303, 519085.853 ...>
 mesh.msh_t
<jigsawpy.msh_t.jigsaw_msh_t object at 0x7f963838fa10>
```

**Versions**
python 3.8.16
OCSMesh 1.1.1 (compiled from source)
shapely 2.0.1
geopandas 0.12.2
pandas 1.5.3
pyarrow 11.0.0
rasterio 1.3.6

**Comment by SorooshMani-NOAA** [comment]
Hi, right now OCSMesh does **not** support `shapely>=2`. Please rebuild your environment using `shapely<2` (#52). Please let me know if the issue persist after downgrading to `shapely<2`.

**Comment by rjdmartins** [comment]
Downgraded Shapely to version 1.8.5 and it's working.

**Comment by SorooshMani-NOAA** [comment]
Thanks for testing! I need to started looking into making OCSMesh compatible with `shapely 2` sometime soon!
