### ISSUE TITLE
Raster+Geom: get_multipolygon() throws "ValueError: If using all scalar values, you must pass an index"

### ISSUE THREAD

**Issue by rjdmartins** [noaa-ocs-modeling/OCSMesh#64]
**Description:**
I'm trying some of the examples provided from this documentation (https://repository.library.noaa.gov/view/noaa/33879), and they do not work in OCSMesh 1.1.1.

The following example is similiar as the Shinnecock one, but applied to Portugal. 
I load a gebco raster with Raster object (r), then create a circle (base_gs), and aggregate them into a Geom object (geom).

```
import os, sys
import json

sys.path.append('/ocsmesh') #ocsmesh source directory

import geopandas as gpd
from shapely.geometry import LineString, MultiLineString, Polygon, Point
from shapely.ops import unary_union, polygonize
from ocsmesh import Raster, Geom, Hfun, Mesh, JigsawDriver, utils
import pyproj

geom_rasters = list()
r = Raster('/_app/raster_examples/gebco_2022_sub_ice_n90.0_s0.0_w-90.0_e0.0.tif')
geom_rasters.append(r)
lon, lat = -9.24253, 38.68361
custom_crs = pyproj.CRS.from_string(f'proj=aeqd +lat_0={lat} +lon_0={lon} +datum=WGS84 +units=m')
base_gs = gpd.GeoSeries(Point([0, 0]).buffer(50e3), crs=custom_crs)
geom = Geom(geom_rasters, base_shape=base_gs.unary_union, base_shape_crs=base_gs.crs, zmax=0)
geom.get_multipolygon()
```

geom.get_multipolygon() must return a MULTIPOLYGON object as output, but instead throws an "ValueError: If using all scalar values, you must pass an index".

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ocsmesh/ocsmesh/geom/collector.py", line 309, in get_multipolygon
    feather_files.append(self._extract_global_boundary(
  File "/ocsmesh/ocsmesh/geom/collector.py", line 590, in _extract_global_boundary
    combine_geometry(
  File "/ocsmesh/ocsmesh/ops/__init__.py", line 5, in combine_geometry
    return GeomCombine(*args, **kwargs).run()
  File "/ocsmesh/ocsmesh/ops/combine_geom.py", line 171, in run
    self._multipolygon_to_disk(
  File "/ocsmesh/ocsmesh/ops/combine_geom.py", line 292, in _multipolygon_to_disk
    gpd.GeoDataFrame({'geometry': multipolygon}).to_feather(path)
  File "/_venv/lib/python3.8/site-packages/geopandas/geodataframe.py", line 135, in __init__
    super().__init__(data, *args, **kwargs)
  File "/_venv/lib/python3.8/site-packages/pandas/core/frame.py", line 664, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/_venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 493, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/_venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 118, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/_venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 656, in _extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index
```

**Versions**
python 3.8.16
OCSMesh 1.1.1 (compiled from source)
shapely 2.0.1
geopandas 0.12.2
pandas 1.5.3
pyarrow 11.0.0
rasterio 1.3.6

**Comment by SorooshMani-NOAA** [comment]
![image](https://user-images.githubusercontent.com/77082694/223829652-9d8fd24d-d791-4053-afce-e1b2df072ebc.png)

I don't see this issue. I suspect that just like #63 this might be related to `shapely>=2`. Can you please downgrade to pre `v2` and test again?

**Comment by rjdmartins** [comment]
I can confirm this is an issue with Shapely version. 
Downgraded Shapely to version 1.8.5 and it's working.
